### ISSUE TITLE
Migrate validation pipeline from GitLab to GitHub

### ISSUE THREAD

**Issue by lobis** [rest-for-physics/framework#45]
- [x] Framework
- [x] [Geant4Lib](https://github.com/rest-for-physics/geant4lib/issues/12)
- [x] [RestG4](https://github.com/rest-for-physics/restG4/issues/10). Include also clang-format.
- [x] [RawLib](https://github.com/rest-for-physics/rawlib/issues/9)
- [x] TrackLib
- [x] ConnectorsLib
- [x] [AxionLib](https://github.com/rest-for-physics/axionlib)
- [x] DetectorLib
- [x] Update README.md badges at each repository
- [ ] Update [CONTRIBUTING.md](https://github.com/rest-for-physics/framework/blob/master/CONTRIBUTING.md) to include a section encouraging to create pipelines and give few guidelines on how to prepare them.

https://docs.github.com/en/actions/learn-github-actions/migrating-from-gitlab-cicd-to-github-actions

**Comment by lobis** [comment]
I have created a milestone and linked issues for the other repositories, it would be nice if we could reference the milestone from the other repos too, (otherwise it makes little sense).

Maybe @jgalan or @juanangp know more about this?

**Comment by jgalan** [comment]
Notice that libraries have a common validation script, where we may introduce rules that guarantee that a library fulfills with certain specifications. I.e. any library must call the method `SetLibraryVersion` at `InitProcess` method.

```
validateLibrary:
    stage: pre-build
    script:
        - python3 pipeline/validateLibrary.py .
    except:
        variables:
            - $CRONJOB == "YES"
```

Then, we are also executing the `clang-format` validation at each repository. This job is not executed at any pipeline, but it is executed only from time to time, it is defined as an scheduled job. It will be launched every week (or day), check if there are any files that do not fulfill with the clang-format specifications, prepare the commit and upload it to the repository.

```
clang-format:
    stage: pre-build
    script:
        - echo "**$CRONJOB**"
        - echo "**$CI_SERVER_HOST**"
        - cd ${CI_PROJECT_DIR}/pipeline/clang-format/
        - ./clangformattest.sh
          # We execute only at a schedulled pipeline that defines CRONJOB variable
    only:
        variables:
            - $CRONJOB
```
